stages:
  - build

slides:
    stage: build
    image: aergus/latex
    # Supports both pandoc and latexmk
    script:
        - make build
    artifacts:
        when: always
        paths:
        - ./slides.pdf



